using TaskFlow.Domain.Enums;

namespace TaskFlow.Domain.Entities;

/// <summary>
/// Represents a registered user of the TaskFlow system.
/// </summary>
public class User
{
    // ─────────────────────────────────────────────────────────
    // Identity
    // ─────────────────────────────────────────────────────────

    /// <summary>Primary key — UUID generated by the application, not the database.</summary>
    public Guid Id { get; set; }

    /// <summary>Unique email address used for login.</summary>
    public string Email { get; set; } = string.Empty;

    /// <summary>BCrypt/PBKDF2 hash of the user's password. Never the plaintext password.</summary>
    public string PasswordHash { get; set; } = string.Empty;

    // ─────────────────────────────────────────────────────────
    // Profile
    // ─────────────────────────────────────────────────────────

    public string FirstName { get; set; } = string.Empty;

    public string LastName { get; set; } = string.Empty;

    // ─────────────────────────────────────────────────────────
    // System fields
    // ─────────────────────────────────────────────────────────

    /// <summary>Global system role. Most users are UserRole.User.</summary>
    public UserRole Role { get; set; } = UserRole.User;

    /// <summary>
    /// Inactive users cannot log in.
    /// Admins can activate/deactivate accounts.
    /// </summary>
    public bool IsActive { get; set; } = true;

    /// <summary>UTC timestamp when the account was created.</summary>
    public DateTime CreatedAt { get; set; }

    /// <summary>UTC timestamp when the account was last modified.</summary>
    public DateTime UpdatedAt { get; set; }

    // ─────────────────────────────────────────────────────────
    // Navigation properties (EF Core relationships)
    // ─────────────────────────────────────────────────────────

    /// <summary>Projects this user created and owns.</summary>
    public ICollection<Project> OwnedProjects { get; set; } = [];

    /// <summary>Projects this user is a member of (via the ProjectMember join table).</summary>
    public ICollection<ProjectMember> ProjectMemberships { get; set; } = [];

    /// <summary>Tasks this user created.</summary>
    public ICollection<TaskItem> CreatedTasks { get; set; } = [];

    /// <summary>Tasks currently assigned to this user.</summary>
    public ICollection<TaskItem> AssignedTasks { get; set; } = [];
}
